name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - uses: actions/upload-artifact@v2
        with:
          name: action-package
          path: |
            action.yml
            dist/*
  test:
    runs-on: ubuntu-latest
    needs: build       
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: action-package
    - name: run test
      uses: ./
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: |
       npm install
       npm run build && npm run package
       PACKAGE_VERSION=$(node -p "require('./package.json').version")
       echo $PACKAGE_VERSION
  


