name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - uses: actions/upload-artifact@v2
        with:
          name: action-package
          path: |
            action.yml
            dist/*
  test:
    runs-on: ubuntu-latest
    needs: build       
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: action-package
    - name: run test
      uses: ./
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[release]')"
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: |
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"                    
       npm install
       npm run build && npm run package
       npm version patch
       git add --all
       git commit -m "new release"
       PACKAGE_VERSION=$(node -p "require('./package.json').version")
       echo $PACKAGE_VERSION
       git tag -fa v$PACKAGE_VERSION -m "Update tag"
       git push origin v$PACKAGE_VERSION --force
  